
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package marla.ide.resource;
			public class BuildInfo {
				public static final String revisionNumber="675";
				public static final String timeStamp="Thu, 21-April-2011 09:30:16 EDT";
			}
		