
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package marla.ide.resource;
			public class BuildInfo {
				public static final String revisionNumber="456";
				public static final String timeStamp="Sun, 27-March-2011 16:38:38 EDT";
			}
		