
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package marla.ide.resource;
			public class BuildInfo {
				public static final String revisionNumber="588";
				public static final String timeStamp="Mon, 4-April-2011 19:07:42 EDT";
			}
		