
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package resource;
			public class BuildInfo {
				public static final String revisionNumber="359";
				public static final String timeStamp="Mon, 21-March-2011 15:33:16 EDT";
			}
		