
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package resource;
			public class BuildInfo {
				public static final String revisionNumber="348";
				public static final String timeStamp="Sun, 20-March-2011 23:09:04 EDT";
			}
		