
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package resource;
			public class BuildInfo {
				public static final String revisionNumber="376";
				public static final String timeStamp="Tue, 22-March-2011 13:36:13 EDT";
			}
		