
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package resource;
			public class BuildInfo {
				public static final String revisionNumber="395";
				public static final String timeStamp="Wed, 23-March-2011 18:28:20 EDT";
			}
		