
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package marla.ide.resource;
			public class BuildInfo {
				public static final String revisionNumber="408";
				public static final String timeStamp="Thu, 24-March-2011 11:54:16 EDT";
			}
		