
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package marla.ide.resource;
			public class BuildInfo {
				public static final String revisionNumber="854";
				public static final String timeStamp="Fri, 29-April-2011 09:59:53 EDT";
			}
		