
			/**
			 * This file is automatically generated by ant on compile and reflects the current svn version.
			 * See main build.xml for generate script.
			 */
			package marla.ide.resource;
			public class BuildInfo {
				public static final String revisionNumber="495";
				public static final String timeStamp="Tue, 29-March-2011 12:49:55 EDT";
			}
		